services:
  krakend:
    container_name: krakend
    build:
      context: ./krakend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app_network

  book-api:
    build:
      context: ./book-api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app_network

  user-management-api:
    build:
      context: ./user-management-api
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge