# Generated by Django 5.2.1 on 2026-02-19 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRequest',
            fields=[
                ('exchange_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'exchange_requests',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='userbook',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('requested', 'Requested'), ('exchanged', 'Exchanged')], default='available', max_length=20),
        ),
        migrations.RemoveField(
            model_name='book',
            name='genres',
        ),
        migrations.AddIndex(
            model_name='userbook',
            index=models.Index(fields=['user', 'status'], name='idx_userbook_user_status'),
        ),
        migrations.AddIndex(
            model_name='userbook',
            index=models.Index(fields=['book_id'], name='idx_userbook_book_id'),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_requests', to='books.userbook'),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['name'], name='idx_book_name'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['author'], name='idx_book_author'),
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, to='books.genre'),
        ),
    ]
